// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD904aYXRPr5JUbNZPYVh2VH7im1qzslIU',
    appId: '1:409823234185:web:9e8eb79ce7a2b599225e58',
    messagingSenderId: '409823234185',
    projectId: 'career-pathfinder-83b14',
    authDomain: 'career-pathfinder-83b14.firebaseapp.com',
    storageBucket: 'career-pathfinder-83b14.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1bOws1oi6sBqiNiFjU_12EySaJ-ep9LA',
    appId: '1:409823234185:android:ed614ca2f3018d21225e58',
    messagingSenderId: '409823234185',
    projectId: 'career-pathfinder-83b14',
    storageBucket: 'career-pathfinder-83b14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1_4PI6cgey-Jb1m8CGMJrZCe-VteVMmg',
    appId: '1:409823234185:ios:dac78526ca969375225e58',
    messagingSenderId: '409823234185',
    projectId: 'career-pathfinder-83b14',
    storageBucket: 'career-pathfinder-83b14.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1_4PI6cgey-Jb1m8CGMJrZCe-VteVMmg',
    appId: '1:409823234185:ios:dac78526ca969375225e58',
    messagingSenderId: '409823234185',
    projectId: 'career-pathfinder-83b14',
    storageBucket: 'career-pathfinder-83b14.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD904aYXRPr5JUbNZPYVh2VH7im1qzslIU',
    appId: '1:409823234185:web:dcf107f6385991fe225e58',
    messagingSenderId: '409823234185',
    projectId: 'career-pathfinder-83b14',
    authDomain: 'career-pathfinder-83b14.firebaseapp.com',
    storageBucket: 'career-pathfinder-83b14.firebasestorage.app',
  );
}
